#TODO FROM tpesout/modules:4.3.0--c999abdc958fe45c735dca093555b5413aecb678
FROM tpesout/modules:latest
MAINTAINER Trevor Pesout, tpesout@ucsc.edu


WORKDIR /root/scripts/stats/
COPY tmp/* ./
WORKDIR /data
