#!/bin/bash
# minimap_long_read 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    echo "Value of input_reads: '${input_reads[@]}'"
    echo "Value of reference: '$reference'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    set -x

    if [ ! -z "$index" ]; then
        dx download "$index" -o ref.mmi
    elif [ ! -z "$reference" ]; then
      dx download "$reference" -o - | zcat > ref.fa
      minimap2 -t 32 -d ref.mmi  ref.fa &
    else
      echo "Must specify reference or index"
      exit 1
    fi

    input_string=""
    for i in ${!input_reads[@]}
    do
        dx download "${input_reads[$i]}" -o reads-$i.fastq.gz
    done

    wait

    preset_opt = ""
    if [ ! -z "$preset" ]; then
      preset_opt = "-x $preset "
    fi

    minimap2 -t 32 -L --MD -a ${preset_opt}-R "@RG\\tID:${sample}\\tPL:PACBIO\\tPU:${sample}\\tLB:${sample}\\tSM:${sample}" ref.mmi *.fastq.gz | samtools view -bhu - | samtools sort - > output.bam

    samtools index output.bam

    output_bam=$(dx upload output.bam -o $sample.minimap2.bam --brief)
    output_bai=$(dx upload output.bam.bai -o $sample.minimap2.bam.bai --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output output_bam "$output_bam" --class=file
    dx-jobutil-add-output output_bai "$output_bai" --class=file
}
