#!/bin/bash
# asm-stats 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.
set -x -e -o pipefail

main() {

    echo "Value of asm: '$asm'"
    echo "Value of gsize: '$gsize'"
    echo "Value of c: '$c'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    dx download "$asm" -o asm.fasta.gz
    gunzip asm.fasta.gz
	
	java -jar -Xmx1g /opt/java/fastaContigSize.jar asm.fasta

    fasta_len=$(dx upload asm.fasta.len --brief)
    
    dx-jobutil-add-output fasta_len "$fasta_len" --class=file
    
    java -jar -Xmx1g /opt/java/lenCalcNGStats.jar $fasta_len $gsize
    
    
    
    dx-jobutil-add-output asm_stats "$asm_stats" --class=file
    
    if [[ "$c" == "c" ]]; then
		exit 0
	fi
	
	N_BASES=`awk '{sum+=$2; sumN+=$3} END {print (sum-sumN)}' $fasta.len`
	echo "N bases: $N_BASES"

}
