#!/bin/bash
# freebayes-sp 0.0.1
# Generated by dx-app-wizard.

set -x -e -o pipefail

main() {

    echo "Value of reference: '$REF'"
    echo "Value of bam: '$BAM'"
    echo "Value of max: '$MAX'"
    echo "Value of nproc: '$NPROC'"

    dx download "$REF" -o reference

    dx download "$BAM" -o bam

	if ! [ -e ${REF}.fai ]; then

	samtools faidx ${REF}

	fi

	if ! [ -e fa ]; then

	mkdir fa

	cat ${REF}| awk '{if (substr($0, 1, 1)==">") {filename=(substr($0,2) ".fa")} print $0 > "fa\/"filename}'

	fi

	if ! [ -e vcf ]; then

	mkdir vcf

	awk '{print $1 "\t" $2}' ${REF}.fai > list
	
	samtools index ${BAM}
	
	cat list | awk -v bam=${BAM} -v ref=${REF} -v max=${MAX} '{a["freebayes --bam "bam" --region \""$1":1-"$2"\" --max-coverage "max" --fasta-reference "ref" --vcf \"vcf/"$1".vcf\""]}END{for(i in a) print i a[i]}' | parallel --gnu -j ${NPROC}

	for f in vcf/*.vcf; do bgzip $f; tabix -p vcf $f.gz; done

	fi

	if ! [ -e fa_pl ]; then

	mkdir fa_pl

	awk '{print $1}' list | awk '{a["/home/gformenti/bin/bcftools/bcftools consensus \"vcf\/"$1".vcf.gz\" -i'\''QUAL>1 && (GT=\"AA\" || GT=\"Aa\")'\'' -Hla -f \"fa\/"$1".fa\" -o \"fa_pl\/"$1".fa\""]}END{for(i in a) print i a[i]}' | parallel --gnu -j ${NPROC}

	fi

	cat $(awk 'BEGIN { ORS = " " } { print "fa_pl\/"$1".fa" }' ${REF}.fai) > ${REF%.*}_pl.fasta

	pl_fasta=$(dx upload ${REF%.*}_pl.fasta --brief)

	dx-jobutil-add-output pl_fasta "$pl_fasta" --class=file
}
